### ISSUE TITLE
Error opening the STT stream 

### ISSUE THREAD

**Issue by PhilippeComte** [IBM/watson-voice-bot#14] opened 2018-09-18 20:29 UTC
Hello , following the instructions to use the app
Application is made available but does not work properly . 
I get: Error opening the STT stream 
Could it be related to the changes in the security model (TLS 1.0 to 1.2 ) ? 
What would you advise to look for ?
Thank you

**Comment by PhilippeComte** [comment] 2018-09-18 20:32
Note :  all services run in the eu-de domain (Frankfurt)

**Comment by stevemart** [comment] 2018-09-19 00:42
@ptrikkur @rameshpoomalai please see above issue. ^

@PhilippeComte can you copy the entire stack trace from the log?

**Comment by ptrikkur** [comment] 2018-09-19 04:40
@stevemart This issue comes up when STT is down. This will resolve itself when STT is up.It is not a defect in the code.

**Comment by PhilippeComte** [comment] 2018-09-19 04:59
Hello 

For the version build on the cloud, it seems that there is a mismatch of credentials 

t message 		
Error: Unauthorized: Access is denied due to invalid credentials , Code: 401 , Information: {u'description': u'2018-09-18T23:53:21-05:00, Error ERCDPLTFRM-DNLKUPERR occurred when accessing https://stream.watsonplatform.net/speech-to-text/api/watson-auth-token?Client-IP=161.156.72.96;Client-CN=;, Tran-Id: stream02-127370781 - Invalid UserId and/or Password. Please confirm that your credentials match the end-point you are trying to access. A common error is trying to use credentials from an experimental or beta release against a GA release or vice versa'} , X-dp-watson-tran-id: stream02-127370685 , X-global-transaction-id: 7a6c26455ba1d641079785bd 

? message_type_str 		
OUT 

	
	

	

Cordialement 
Philippe Comte 
+33 676861847 

----- Mail original -----

De: "Steve Martinelli" <notifications@github.com> 
À: "IBM/watson-voice-bot" <watson-voice-bot@noreply.github.com> 
Cc: "Philippe Comte" <philippe_comte@laposte.net>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 19 Septembre 2018 02:42:19 
Objet: Re: [IBM/watson-voice-bot] Error opening the STT stream (#14) 



@ptrikkur @rameshpoomalai please see above issue. ^ 

@PhilippeComte can you copy the entire stack trace from the log?

**Comment by ptrikkur** [comment] 2018-09-19 06:50
@PhilippeComte  Are you deploying the application locally? If yes then have you edited .env and added in the credentials for the STT service?
 #Watson Speech To Text
SPEECHTOTEXT_USER=<add_stt_username>
SPEECHTOTEXT_PASSWORD=<add stt password>

**Comment by scottdangelo** [comment] 2018-09-27 16:32
@PhilippeComte I believe the problem was coming from changes to the watson-developer-cloud SDK version 2.x
I've pinned the requirement to version 1.5 and it seems to be working.
Please pull the latest version from Master branch and re-try.

**Comment by stevemart** [comment] 2019-02-19 20:57
@scottdangelo will try to reproduce

**Comment by scottdangelo** [comment] 2019-02-20 22:08
I cannot reproduce this in the Dallas region. I'm going to close this, but please re-open if you are still having troubles @PhilippeComte .
Thanks.

**Closed by scottdangelo** 2019-02-20 22:08 UTC

**Comment by DarleySaavedra** [comment] 2019-09-04 04:52
Hola, me podrian pasarme las credenciales, porfavor

**Comment by ptrikkur** [comment] 2019-09-04 05:01
Qué credenciales necesitas?

**Comment by DarleySaavedra** [comment] 2019-09-06 03:37
[image: image.png]
Se encuentra cerrado en esta sesión por la cual pasé a leer en los
comentario donde hay un enlace:
https://stream.watsonplatform.net/speech-to-text/api/watson-auth-token?Client-IP=161.156.72.96;Client-CN=
aquí ismo donde abro el enlace me pide los credenciales. Por eso pedía si
fuera muy amable de pasarme las credenciales, gracias.
